apiVersion: v1
appVersion: 1.10.0
description: A Helm chart for the AWS Node Termination Handler
home: https://github.com/aws/eks-charts
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
keywords:
- eks
- ec2
- node-termination
- spot
maintainers:
- email: bwagner5@users.noreply.github.com
  name: Brandon Wagner
  url: https://github.com/bwagner5
- email: jillmon@users.noreply.github.com
  name: Jillian Montalvo
  url: https://github.com/jillmon
name: aws-node-termination-handler
sources:
- https://github.com/aws/eks-charts
version: 0.12.0
