# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 https://aws.amazon.com/apache-2-0/
enableSqsTerminationDraining: true
enablePrometheusServer: true

image:
  repository: ${aws_htc_ecr}/ecr-public/aws-ec2/aws-node-termination-handler

tolerations:
  - key: "grid/type"
    operator: "Equal"
    value: "Operator"
    effect: "NoSchedule"

rbac:
  pspEnabled: false





