# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 https://aws.amazon.com/apache-2-0/
clusterName: ${eks_cluster_id}
region: ${region}
logLevel: "debug"
enableShield: false
enableWaf: false
enableWafv2: false

image:
  repository: "602401143452.dkr.ecr.${region}.amazonaws.com/amazon/aws-load-balancer-controller"
nodeSelector:
  grid/type: "Operator"

tolerations:
  - key: "grid/type"
    operator: "Equal"
    value: "Operator"
    effect: "NoSchedule"






