# Copyright 2023 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 https://aws.amazon.com/apache-2-0/

name: Test-Flake8
on: [push, pull_request]

jobs:
  flake:
    runs-on: ubuntu-latest
    env:
      NEW_BRANCH: new_branch
      MAIN_BRANCH: main_branch
      NEW_BRANCH_REPORT_FILE: new_branch_flake_report_file.txt
      MAIN_BRANCH_REPORT_FILE: main_branch_flake_report_file.txt
      DIFF_REPORTS_FILE: diff_reports.txt

    steps:
      - name: Checkout the modified branch
        uses: actions/checkout@v3
        with: 
          path: ${{ env.NEW_BRANCH }}

      - name: Checkout the main branch
        uses: actions/checkout@v3
        with:
          repository: awslabs/aws-htc-grid
          path: ${{ env.MAIN_BRANCH }}

      - name: Install flake8
        run: |-
          pip3 install flake8
          ls -l -a
          pwd

      - name: Run flake8 on the new branch
        run: cd ./${{ env.NEW_BRANCH }}/ && flake8 --config ./.github/workflows/flake8.config --exit-zero ./ --output-file ./../${{ env.NEW_BRANCH_REPORT_FILE }} && cd ./../

      - name: Run flake8 on the main branch
        run: cd ./${{ env.MAIN_BRANCH }}/ && flake8 --config ./../${{ env.NEW_BRANCH }}/.github/workflows/flake8.config --exit-zero ./ --output-file ./../${{ env.MAIN_BRANCH_REPORT_FILE }} && cd ./../

      - name: Save report results for the new branch
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.NEW_BRANCH_REPORT_FILE }}
          path: ${{ env.NEW_BRANCH_REPORT_FILE }}

      - name: Save report results for the main branch
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.MAIN_BRANCH_REPORT_FILE }}
          path: ${{ env.MAIN_BRANCH_REPORT_FILE }}

      - name: check
        run: |-
          diff ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH_REPORT_FILE }} >> ${{ env.DIFF_REPORTS_FILE }} || true

      - name: Save diff reports
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.DIFF_REPORTS_FILE }}
          path: ${{ env.DIFF_REPORTS_FILE }}

      - name: Verify that the number of errors in the new branch does not exceeding the number of existing errors in the main branch.
        run: |-          
          echo 'if [ "$(wc -l < $1 )" -gt "$(wc -l < $2 )" ]; then echo "Warning New branch has more errors!"; exit 1; fi; exit 0' >> script.sh
          ls -l -a
          bash ./script.sh ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH_REPORT_FILE }}
