# Copyright 2023 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 https://aws.amazon.com/apache-2-0/

name: Test-Trivy
on: [push, pull_request]

jobs:
  trivy:
    runs-on: ubuntu-latest
    env:
      NEW_BRANCH: new_branch
      MAIN_BRANCH: main_branch
      NEW_BRANCH_REPORT_FILE: new_branch_trivy_report_file.json
      MAIN_BRANCH_REPORT_FILE: main_branch_trivy_report_file.json
      DIFF_REPORTS_FILE: diff_trivy_reports.txt

    steps:
      - name: Checkout the new branch
        uses: actions/checkout@v3
        with: 
          path: ${{ env.NEW_BRANCH }}

      - name: Checkout the main branch
        uses: actions/checkout@v3
        with:
          repository: awslabs/aws-htc-grid
          path: ${{ env.MAIN_BRANCH }}

      - name: Run Trivy in fs mode on the new branch
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: ${{ env.NEW_BRANCH }}
          ignore-unfixed: true
          severity: UNKNOWN,MEDIUM,HIGH,CRITICAL
          trivy-config: "${{ env.NEW_BRANCH }}/.github/workflows/trivy.conf"
          # output: ${{ env.NEW_BRANCH_REPORT_FILE }} # This flag doesnt seem to be working.
        env:
          TRIVY_OUTPUT: ${{ env.NEW_BRANCH_REPORT_FILE }}

      - name: Run Trivy in fs mode on the main branch
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: ${{ env.MAIN_BRANCH }}
          ignore-unfixed: true
          severity: UNKNOWN,MEDIUM,HIGH,CRITICAL
          trivy-config: "${{ env.NEW_BRANCH }}/.github/workflows/trivy.conf"
          # output: ${{ env.MAIN_BRANCH_REPORT_FILE }} # This flag doesnt seem to be working.
        env:
          TRIVY_OUTPUT: ${{ env.MAIN_BRANCH_REPORT_FILE }}

      # This action can be enabled when using GitHub Security Code Scanning feature
      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v2
      #   if: success() || failure()
      #   with:
      #     sarif_file: "${{ env.NEW_BRANCH_REPORT_FILE }}"

      - name: Save report results for the new branch
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.NEW_BRANCH_REPORT_FILE }}
          path: ${{ env.NEW_BRANCH_REPORT_FILE }}

      - name: Save report results for the main branch
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.MAIN_BRANCH_REPORT_FILE }}
          path: ${{ env.MAIN_BRANCH_REPORT_FILE }}

      - name: Generate the diff of reports between main and the new branch
        run: |-
          diff ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH_REPORT_FILE }} >> ${{ env.DIFF_REPORTS_FILE }} || true

      - name: Save diff reports
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.DIFF_REPORTS_FILE }}
          path: ${{ env.DIFF_REPORTS_FILE }}

      - name: Verify that the number of errors in the new branch does not exceed the number of existing errors in the main branch
        run: |-          
          if [ "$(wc -l < ${{ env.NEW_BRANCH_REPORT_FILE }} )" -gt "$(wc -l < ${{ env.MAIN_BRANCH_REPORT_FILE }} )" ]; then \
            echo "Warning: New branch has more errors!"
            exit 1
          fi
